/********************************************************************************
** Form generated from reading UI file 'gamescreen.ui'
**
** Created by: Qt User Interface Compiler version 5.15.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GAMESCREEN_H
#define UI_GAMESCREEN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GameScreen
{
public:
    QHBoxLayout *horizontalLayout_2;
    QStackedWidget *stackedWidget;
    QWidget *Auction;
    QLabel *lblInfo;
    QTableWidget *tableBids;
    QPushButton *pushButton_Pass;
    QPushButton *pushButton_Double;
    QPushButton *pushButton_Bid;
    QPushButton *pushButton_Play;
    QWidget *layoutWidget;
    QVBoxLayout *verticalLayout;
    QLabel *lblContract;
    QLabel *lblDeclarer;
    QLabel *lblDummy;
    QLabel *lblDouble;
    QPushButton *pushButton_ViewCards;
    QPushButton *pushButton_Redouble;
    QTableWidget *tableSequence;
    QLabel *lblPosition;
    QWidget *Play;
    QLabel *lblInfoPlay;
    QLabel *lblTeam;
    QLabel *lblPlayer;
    QLabel *lblOpp2;
    QLabel *lblOpp1;
    QLabel *lblOpp2Name;
    QLabel *lblNameTeam;
    QLabel *lblOpp1Name;
    QLabel *lblNamePlayer;
    QPushButton *pushButton_Score;
    QPushButton *pushButton_Abandon;
    QWidget *layoutWidget1;
    QVBoxLayout *verticalLayout_2;
    QLabel *lblVulnerable;
    QLabel *lblPoints;
    QLabel *lblContractPlay;
    QLabel *lblRoundInfo;
    QPushButton *pushButton_BackAuction;
    QPushButton *pb_1;
    QPushButton *pb_2;
    QPushButton *pb_3;
    QPushButton *pb_4;
    QPushButton *pb_5;
    QPushButton *pb_6;
    QPushButton *pb_7;
    QPushButton *pb_8;
    QPushButton *pb_9;
    QPushButton *pb_10;
    QPushButton *pb_11;
    QPushButton *pb_12;
    QPushButton *pb_13;
    QPushButton *pb_14;
    QPushButton *pb_15;
    QPushButton *pb_16;
    QPushButton *pb_17;
    QPushButton *pb_18;
    QPushButton *pb_19;
    QPushButton *pb_20;
    QPushButton *pb_21;
    QPushButton *pb_22;
    QPushButton *pb_23;
    QPushButton *pb_24;
    QPushButton *pb_25;
    QPushButton *pb_26;
    QPushButton *pb_Move_1;
    QPushButton *pb_Move_2;
    QPushButton *pb_Move_3;
    QPushButton *pb_Move_4;
    QLabel *lblTricksWonNS;
    QLabel *lblTricksWonEW;

    void setupUi(QDialog *GameScreen)
    {
        if (GameScreen->objectName().isEmpty())
            GameScreen->setObjectName(QString::fromUtf8("GameScreen"));
        GameScreen->resize(1194, 896);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(0, 86, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        GameScreen->setPalette(palette);
        horizontalLayout_2 = new QHBoxLayout(GameScreen);
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        stackedWidget = new QStackedWidget(GameScreen);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        QPalette palette1;
        QBrush brush2(QColor(240, 240, 240, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        stackedWidget->setPalette(palette1);
        stackedWidget->setCursor(QCursor(Qt::ArrowCursor));
        Auction = new QWidget();
        Auction->setObjectName(QString::fromUtf8("Auction"));
        lblInfo = new QLabel(Auction);
        lblInfo->setObjectName(QString::fromUtf8("lblInfo"));
        lblInfo->setGeometry(QRect(0, 0, 821, 61));
        QFont font;
        font.setPointSize(12);
        font.setBold(false);
        font.setItalic(true);
        font.setWeight(50);
        lblInfo->setFont(font);
        tableBids = new QTableWidget(Auction);
        if (tableBids->columnCount() < 5)
            tableBids->setColumnCount(5);
        if (tableBids->rowCount() < 7)
            tableBids->setRowCount(7);
        QFont font1;
        font1.setPointSize(24);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        __qtablewidgetitem->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem->setFont(font1);
        tableBids->setItem(0, 0, __qtablewidgetitem);
        QBrush brush3(QColor(255, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        QBrush brush4(QColor(170, 0, 0, 255));
        brush4.setStyle(Qt::NoBrush);
        QFont font2;
        font2.setPointSize(24);
        font2.setKerning(false);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        __qtablewidgetitem1->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem1->setFont(font2);
        __qtablewidgetitem1->setBackground(brush4);
        __qtablewidgetitem1->setForeground(brush3);
        tableBids->setItem(0, 1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        __qtablewidgetitem2->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem2->setFont(font2);
        __qtablewidgetitem2->setForeground(brush3);
        tableBids->setItem(0, 2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        __qtablewidgetitem3->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem3->setFont(font1);
        tableBids->setItem(0, 3, __qtablewidgetitem3);
        QFont font3;
        font3.setPointSize(20);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        __qtablewidgetitem4->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem4->setFont(font3);
        tableBids->setItem(0, 4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        __qtablewidgetitem5->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem5->setFont(font1);
        tableBids->setItem(1, 0, __qtablewidgetitem5);
        QBrush brush5(QColor(170, 0, 0, 255));
        brush5.setStyle(Qt::NoBrush);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        __qtablewidgetitem6->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem6->setFont(font2);
        __qtablewidgetitem6->setBackground(brush5);
        __qtablewidgetitem6->setForeground(brush3);
        tableBids->setItem(1, 1, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        __qtablewidgetitem7->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem7->setFont(font2);
        __qtablewidgetitem7->setForeground(brush3);
        tableBids->setItem(1, 2, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        __qtablewidgetitem8->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem8->setFont(font1);
        tableBids->setItem(1, 3, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        __qtablewidgetitem9->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem9->setFont(font3);
        tableBids->setItem(1, 4, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        __qtablewidgetitem10->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem10->setFont(font1);
        tableBids->setItem(2, 0, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        __qtablewidgetitem11->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem11->setFont(font2);
        __qtablewidgetitem11->setForeground(brush3);
        tableBids->setItem(2, 1, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        __qtablewidgetitem12->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem12->setFont(font2);
        __qtablewidgetitem12->setForeground(brush3);
        tableBids->setItem(2, 2, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        __qtablewidgetitem13->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem13->setFont(font1);
        tableBids->setItem(2, 3, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        __qtablewidgetitem14->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem14->setFont(font3);
        tableBids->setItem(2, 4, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        __qtablewidgetitem15->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem15->setFont(font1);
        tableBids->setItem(3, 0, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        __qtablewidgetitem16->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem16->setFont(font2);
        __qtablewidgetitem16->setForeground(brush3);
        tableBids->setItem(3, 1, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        __qtablewidgetitem17->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem17->setFont(font2);
        __qtablewidgetitem17->setForeground(brush3);
        tableBids->setItem(3, 2, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        __qtablewidgetitem18->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem18->setFont(font1);
        tableBids->setItem(3, 3, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        __qtablewidgetitem19->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem19->setFont(font3);
        tableBids->setItem(3, 4, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        __qtablewidgetitem20->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem20->setFont(font1);
        tableBids->setItem(4, 0, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        __qtablewidgetitem21->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem21->setFont(font2);
        __qtablewidgetitem21->setForeground(brush3);
        tableBids->setItem(4, 1, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        __qtablewidgetitem22->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem22->setFont(font2);
        __qtablewidgetitem22->setForeground(brush3);
        tableBids->setItem(4, 2, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        __qtablewidgetitem23->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem23->setFont(font1);
        tableBids->setItem(4, 3, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        __qtablewidgetitem24->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem24->setFont(font3);
        tableBids->setItem(4, 4, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        __qtablewidgetitem25->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem25->setFont(font1);
        tableBids->setItem(5, 0, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        __qtablewidgetitem26->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem26->setFont(font2);
        __qtablewidgetitem26->setForeground(brush3);
        tableBids->setItem(5, 1, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        __qtablewidgetitem27->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem27->setFont(font2);
        __qtablewidgetitem27->setForeground(brush3);
        tableBids->setItem(5, 2, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        __qtablewidgetitem28->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem28->setFont(font1);
        tableBids->setItem(5, 3, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        __qtablewidgetitem29->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem29->setFont(font3);
        tableBids->setItem(5, 4, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        __qtablewidgetitem30->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem30->setFont(font1);
        tableBids->setItem(6, 0, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        __qtablewidgetitem31->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem31->setFont(font2);
        __qtablewidgetitem31->setForeground(brush3);
        __qtablewidgetitem31->setFlags(Qt::ItemIsSelectable|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        tableBids->setItem(6, 1, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        __qtablewidgetitem32->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem32->setFont(font2);
        __qtablewidgetitem32->setForeground(brush3);
        tableBids->setItem(6, 2, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        __qtablewidgetitem33->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem33->setFont(font1);
        tableBids->setItem(6, 3, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        __qtablewidgetitem34->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem34->setFont(font3);
        tableBids->setItem(6, 4, __qtablewidgetitem34);
        tableBids->setObjectName(QString::fromUtf8("tableBids"));
        tableBids->setGeometry(QRect(710, 120, 451, 491));
        QFont font4;
        font4.setPointSize(16);
        font4.setBold(false);
        font4.setWeight(50);
        tableBids->setFont(font4);
        tableBids->setLayoutDirection(Qt::LeftToRight);
        tableBids->setFrameShape(QFrame::Box);
        tableBids->setFrameShadow(QFrame::Plain);
        tableBids->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableBids->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableBids->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableBids->setDragDropOverwriteMode(false);
        tableBids->setSelectionMode(QAbstractItemView::SingleSelection);
        tableBids->setCornerButtonEnabled(true);
        tableBids->setRowCount(7);
        tableBids->setColumnCount(5);
        tableBids->horizontalHeader()->setVisible(false);
        tableBids->horizontalHeader()->setCascadingSectionResizes(false);
        tableBids->horizontalHeader()->setDefaultSectionSize(84);
        tableBids->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        tableBids->horizontalHeader()->setStretchLastSection(false);
        tableBids->verticalHeader()->setDefaultSectionSize(69);
        tableBids->verticalHeader()->setStretchLastSection(false);
        pushButton_Pass = new QPushButton(Auction);
        pushButton_Pass->setObjectName(QString::fromUtf8("pushButton_Pass"));
        pushButton_Pass->setGeometry(QRect(730, 620, 191, 71));
        pushButton_Pass->setFont(font3);
        pushButton_Double = new QPushButton(Auction);
        pushButton_Double->setObjectName(QString::fromUtf8("pushButton_Double"));
        pushButton_Double->setGeometry(QRect(970, 620, 191, 71));
        pushButton_Double->setFont(font3);
        pushButton_Bid = new QPushButton(Auction);
        pushButton_Bid->setObjectName(QString::fromUtf8("pushButton_Bid"));
        pushButton_Bid->setGeometry(QRect(970, 710, 191, 71));
        pushButton_Bid->setFont(font3);
        pushButton_Play = new QPushButton(Auction);
        pushButton_Play->setObjectName(QString::fromUtf8("pushButton_Play"));
        pushButton_Play->setGeometry(QRect(490, 790, 191, 71));
        pushButton_Play->setFont(font3);
        layoutWidget = new QWidget(Auction);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(10, 630, 296, 201));
        verticalLayout = new QVBoxLayout(layoutWidget);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        lblContract = new QLabel(layoutWidget);
        lblContract->setObjectName(QString::fromUtf8("lblContract"));
        QFont font5;
        font5.setPointSize(16);
        font5.setBold(true);
        font5.setWeight(75);
        lblContract->setFont(font5);

        verticalLayout->addWidget(lblContract);

        lblDeclarer = new QLabel(layoutWidget);
        lblDeclarer->setObjectName(QString::fromUtf8("lblDeclarer"));
        lblDeclarer->setFont(font5);

        verticalLayout->addWidget(lblDeclarer);

        lblDummy = new QLabel(layoutWidget);
        lblDummy->setObjectName(QString::fromUtf8("lblDummy"));
        lblDummy->setFont(font5);

        verticalLayout->addWidget(lblDummy);

        lblDouble = new QLabel(layoutWidget);
        lblDouble->setObjectName(QString::fromUtf8("lblDouble"));
        lblDouble->setFont(font5);

        verticalLayout->addWidget(lblDouble);

        pushButton_ViewCards = new QPushButton(Auction);
        pushButton_ViewCards->setObjectName(QString::fromUtf8("pushButton_ViewCards"));
        pushButton_ViewCards->setEnabled(true);
        pushButton_ViewCards->setGeometry(QRect(490, 710, 191, 71));
        pushButton_ViewCards->setFont(font3);
        pushButton_Redouble = new QPushButton(Auction);
        pushButton_Redouble->setObjectName(QString::fromUtf8("pushButton_Redouble"));
        pushButton_Redouble->setGeometry(QRect(730, 710, 191, 71));
        pushButton_Redouble->setFont(font3);
        tableSequence = new QTableWidget(Auction);
        if (tableSequence->columnCount() < 4)
            tableSequence->setColumnCount(4);
        QFont font6;
        font6.setPointSize(15);
        font6.setBold(true);
        font6.setWeight(75);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        __qtablewidgetitem35->setFont(font6);
        tableSequence->setHorizontalHeaderItem(0, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        __qtablewidgetitem36->setFont(font6);
        tableSequence->setHorizontalHeaderItem(1, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        __qtablewidgetitem37->setFont(font6);
        tableSequence->setHorizontalHeaderItem(2, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        __qtablewidgetitem38->setFont(font6);
        tableSequence->setHorizontalHeaderItem(3, __qtablewidgetitem38);
        if (tableSequence->rowCount() < 11)
            tableSequence->setRowCount(11);
        tableSequence->setObjectName(QString::fromUtf8("tableSequence"));
        tableSequence->setGeometry(QRect(10, 120, 601, 491));
        tableSequence->setFrameShape(QFrame::StyledPanel);
        tableSequence->setSizeAdjustPolicy(QAbstractScrollArea::AdjustIgnored);
        tableSequence->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableSequence->setTabKeyNavigation(false);
        tableSequence->setAlternatingRowColors(false);
        tableSequence->setSelectionMode(QAbstractItemView::NoSelection);
        tableSequence->setRowCount(11);
        tableSequence->setColumnCount(4);
        tableSequence->horizontalHeader()->setVisible(false);
        tableSequence->horizontalHeader()->setDefaultSectionSize(147);
        tableSequence->verticalHeader()->setVisible(false);
        tableSequence->verticalHeader()->setDefaultSectionSize(40);
        lblPosition = new QLabel(Auction);
        lblPosition->setObjectName(QString::fromUtf8("lblPosition"));
        lblPosition->setGeometry(QRect(10, 70, 321, 45));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        QBrush brush6(QColor(120, 120, 120, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        lblPosition->setPalette(palette2);
        QFont font7;
        font7.setPointSize(28);
        font7.setBold(false);
        font7.setWeight(50);
        lblPosition->setFont(font7);
        stackedWidget->addWidget(Auction);
        Play = new QWidget();
        Play->setObjectName(QString::fromUtf8("Play"));
        lblInfoPlay = new QLabel(Play);
        lblInfoPlay->setObjectName(QString::fromUtf8("lblInfoPlay"));
        lblInfoPlay->setGeometry(QRect(0, -10, 821, 61));
        lblInfoPlay->setFont(font);
        lblTeam = new QLabel(Play);
        lblTeam->setObjectName(QString::fromUtf8("lblTeam"));
        lblTeam->setGeometry(QRect(350, 20, 421, 91));
        QFont font8;
        font8.setPointSize(30);
        lblTeam->setFont(font8);
        lblTeam->setAlignment(Qt::AlignCenter);
        lblPlayer = new QLabel(Play);
        lblPlayer->setObjectName(QString::fromUtf8("lblPlayer"));
        lblPlayer->setGeometry(QRect(340, 760, 441, 91));
        lblPlayer->setFont(font8);
        lblPlayer->setAlignment(Qt::AlignCenter);
        lblOpp2 = new QLabel(Play);
        lblOpp2->setObjectName(QString::fromUtf8("lblOpp2"));
        lblOpp2->setGeometry(QRect(10, 390, 251, 211));
        lblOpp2->setFont(font8);
        lblOpp2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        lblOpp2->setWordWrap(true);
        lblOpp1 = new QLabel(Play);
        lblOpp1->setObjectName(QString::fromUtf8("lblOpp1"));
        lblOpp1->setGeometry(QRect(930, 400, 231, 211));
        QPalette palette3;
        QBrush brush7(QColor(0, 0, 0, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        lblOpp1->setPalette(palette3);
        lblOpp1->setFont(font8);
        lblOpp1->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        lblOpp1->setWordWrap(true);
        lblOpp2Name = new QLabel(Play);
        lblOpp2Name->setObjectName(QString::fromUtf8("lblOpp2Name"));
        lblOpp2Name->setGeometry(QRect(30, 380, 91, 16));
        lblNameTeam = new QLabel(Play);
        lblNameTeam->setObjectName(QString::fromUtf8("lblNameTeam"));
        lblNameTeam->setGeometry(QRect(510, 100, 121, 16));
        QFont font9;
        font9.setPointSize(10);
        lblNameTeam->setFont(font9);
        lblOpp1Name = new QLabel(Play);
        lblOpp1Name->setObjectName(QString::fromUtf8("lblOpp1Name"));
        lblOpp1Name->setGeometry(QRect(1000, 390, 91, 16));
        lblNamePlayer = new QLabel(Play);
        lblNamePlayer->setObjectName(QString::fromUtf8("lblNamePlayer"));
        lblNamePlayer->setGeometry(QRect(530, 840, 91, 16));
        lblNamePlayer->setFont(font9);
        pushButton_Score = new QPushButton(Play);
        pushButton_Score->setObjectName(QString::fromUtf8("pushButton_Score"));
        pushButton_Score->setGeometry(QRect(1020, 830, 141, 31));
        pushButton_Score->setFont(font9);
        pushButton_Abandon = new QPushButton(Play);
        pushButton_Abandon->setObjectName(QString::fromUtf8("pushButton_Abandon"));
        pushButton_Abandon->setGeometry(QRect(0, 50, 131, 31));
        pushButton_Abandon->setFont(font9);
        layoutWidget1 = new QWidget(Play);
        layoutWidget1->setObjectName(QString::fromUtf8("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(0, 780, 264, 88));
        verticalLayout_2 = new QVBoxLayout(layoutWidget1);
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        verticalLayout_2->setContentsMargins(0, 0, 0, 0);
        lblVulnerable = new QLabel(layoutWidget1);
        lblVulnerable->setObjectName(QString::fromUtf8("lblVulnerable"));
        QPalette palette4;
        QBrush brush8(QColor(255, 255, 0, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush8);
        QBrush brush9(QColor(255, 255, 0, 128));
        brush9.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush8);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        QBrush brush10(QColor(0, 0, 0, 128));
        brush10.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush10);
#endif
        lblVulnerable->setPalette(palette4);
        QFont font10;
        font10.setPointSize(12);
        lblVulnerable->setFont(font10);
        lblVulnerable->setAutoFillBackground(false);
        lblVulnerable->setTextFormat(Qt::PlainText);

        verticalLayout_2->addWidget(lblVulnerable);

        lblPoints = new QLabel(layoutWidget1);
        lblPoints->setObjectName(QString::fromUtf8("lblPoints"));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        lblPoints->setPalette(palette5);
        lblPoints->setFont(font10);

        verticalLayout_2->addWidget(lblPoints);

        lblContractPlay = new QLabel(layoutWidget1);
        lblContractPlay->setObjectName(QString::fromUtf8("lblContractPlay"));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        lblContractPlay->setPalette(palette6);
        lblContractPlay->setFont(font10);

        verticalLayout_2->addWidget(lblContractPlay);

        lblRoundInfo = new QLabel(Play);
        lblRoundInfo->setObjectName(QString::fromUtf8("lblRoundInfo"));
        lblRoundInfo->setGeometry(QRect(450, 560, 541, 31));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush8);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush8);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush10);
#endif
        lblRoundInfo->setPalette(palette7);
        QFont font11;
        font11.setPointSize(16);
        lblRoundInfo->setFont(font11);
        lblRoundInfo->setAutoFillBackground(false);
        lblRoundInfo->setTextFormat(Qt::PlainText);
        pushButton_BackAuction = new QPushButton(Play);
        pushButton_BackAuction->setObjectName(QString::fromUtf8("pushButton_BackAuction"));
        pushButton_BackAuction->setGeometry(QRect(920, 800, 251, 71));
        pushButton_BackAuction->setFont(font3);
        pb_1 = new QPushButton(Play);
        pb_1->setObjectName(QString::fromUtf8("pb_1"));
        pb_1->setGeometry(QRect(0, 610, 91, 161));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_1->setPalette(palette8);
        pb_1->setAutoFillBackground(true);
        pb_1->setFlat(true);
        pb_2 = new QPushButton(Play);
        pb_2->setObjectName(QString::fromUtf8("pb_2"));
        pb_2->setGeometry(QRect(90, 610, 91, 161));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_2->setPalette(palette9);
        pb_2->setAutoFillBackground(true);
        pb_2->setFlat(true);
        pb_3 = new QPushButton(Play);
        pb_3->setObjectName(QString::fromUtf8("pb_3"));
        pb_3->setGeometry(QRect(180, 610, 91, 161));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_3->setPalette(palette10);
        pb_3->setAutoFillBackground(true);
        pb_3->setFlat(true);
        pb_4 = new QPushButton(Play);
        pb_4->setObjectName(QString::fromUtf8("pb_4"));
        pb_4->setGeometry(QRect(270, 610, 91, 161));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_4->setPalette(palette11);
        pb_4->setAutoFillBackground(true);
        pb_4->setFlat(true);
        pb_5 = new QPushButton(Play);
        pb_5->setObjectName(QString::fromUtf8("pb_5"));
        pb_5->setGeometry(QRect(360, 610, 91, 161));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_5->setPalette(palette12);
        pb_5->setAutoFillBackground(true);
        pb_5->setFlat(true);
        pb_6 = new QPushButton(Play);
        pb_6->setObjectName(QString::fromUtf8("pb_6"));
        pb_6->setGeometry(QRect(450, 610, 91, 161));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_6->setPalette(palette13);
        pb_6->setAutoFillBackground(true);
        pb_6->setFlat(true);
        pb_7 = new QPushButton(Play);
        pb_7->setObjectName(QString::fromUtf8("pb_7"));
        pb_7->setGeometry(QRect(540, 610, 91, 161));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_7->setPalette(palette14);
        pb_7->setAutoFillBackground(true);
        pb_7->setStyleSheet(QString::fromUtf8(""));
        pb_7->setFlat(true);
        pb_8 = new QPushButton(Play);
        pb_8->setObjectName(QString::fromUtf8("pb_8"));
        pb_8->setGeometry(QRect(630, 610, 91, 161));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_8->setPalette(palette15);
        pb_8->setAutoFillBackground(true);
        pb_8->setFlat(true);
        pb_9 = new QPushButton(Play);
        pb_9->setObjectName(QString::fromUtf8("pb_9"));
        pb_9->setGeometry(QRect(720, 610, 91, 161));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_9->setPalette(palette16);
        pb_9->setAutoFillBackground(true);
        pb_9->setFlat(true);
        pb_10 = new QPushButton(Play);
        pb_10->setObjectName(QString::fromUtf8("pb_10"));
        pb_10->setGeometry(QRect(810, 610, 91, 161));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_10->setPalette(palette17);
        pb_10->setAutoFillBackground(true);
        pb_10->setFlat(true);
        pb_11 = new QPushButton(Play);
        pb_11->setObjectName(QString::fromUtf8("pb_11"));
        pb_11->setGeometry(QRect(900, 610, 91, 161));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_11->setPalette(palette18);
        pb_11->setAutoFillBackground(true);
        pb_11->setFlat(true);
        pb_12 = new QPushButton(Play);
        pb_12->setObjectName(QString::fromUtf8("pb_12"));
        pb_12->setGeometry(QRect(990, 610, 91, 161));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_12->setPalette(palette19);
        pb_12->setAutoFillBackground(true);
        pb_12->setFlat(true);
        pb_13 = new QPushButton(Play);
        pb_13->setObjectName(QString::fromUtf8("pb_13"));
        pb_13->setGeometry(QRect(1080, 610, 91, 161));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_13->setPalette(palette20);
        pb_13->setAutoFillBackground(true);
        pb_13->setFlat(true);
        pb_14 = new QPushButton(Play);
        pb_14->setObjectName(QString::fromUtf8("pb_14"));
        pb_14->setGeometry(QRect(0, 120, 91, 161));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_14->setPalette(palette21);
        pb_14->setAutoFillBackground(true);
        pb_14->setFlat(true);
        pb_15 = new QPushButton(Play);
        pb_15->setObjectName(QString::fromUtf8("pb_15"));
        pb_15->setGeometry(QRect(90, 120, 91, 161));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_15->setPalette(palette22);
        pb_15->setAutoFillBackground(true);
        pb_15->setFlat(true);
        pb_16 = new QPushButton(Play);
        pb_16->setObjectName(QString::fromUtf8("pb_16"));
        pb_16->setGeometry(QRect(180, 120, 91, 161));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_16->setPalette(palette23);
        pb_16->setAutoFillBackground(true);
        pb_16->setFlat(true);
        pb_17 = new QPushButton(Play);
        pb_17->setObjectName(QString::fromUtf8("pb_17"));
        pb_17->setGeometry(QRect(270, 120, 91, 161));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette24.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_17->setPalette(palette24);
        pb_17->setAutoFillBackground(true);
        pb_17->setFlat(true);
        pb_18 = new QPushButton(Play);
        pb_18->setObjectName(QString::fromUtf8("pb_18"));
        pb_18->setGeometry(QRect(360, 120, 91, 161));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_18->setPalette(palette25);
        pb_18->setAutoFillBackground(true);
        pb_18->setFlat(true);
        pb_19 = new QPushButton(Play);
        pb_19->setObjectName(QString::fromUtf8("pb_19"));
        pb_19->setGeometry(QRect(450, 120, 91, 161));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette26.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_19->setPalette(palette26);
        pb_19->setAutoFillBackground(true);
        pb_19->setStyleSheet(QString::fromUtf8(""));
        pb_19->setFlat(true);
        pb_20 = new QPushButton(Play);
        pb_20->setObjectName(QString::fromUtf8("pb_20"));
        pb_20->setGeometry(QRect(540, 120, 91, 161));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette27.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_20->setPalette(palette27);
        pb_20->setAutoFillBackground(true);
        pb_20->setFlat(true);
        pb_21 = new QPushButton(Play);
        pb_21->setObjectName(QString::fromUtf8("pb_21"));
        pb_21->setGeometry(QRect(630, 120, 91, 161));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_21->setPalette(palette28);
        pb_21->setAutoFillBackground(true);
        pb_21->setFlat(true);
        pb_22 = new QPushButton(Play);
        pb_22->setObjectName(QString::fromUtf8("pb_22"));
        pb_22->setGeometry(QRect(720, 120, 91, 161));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette29.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_22->setPalette(palette29);
        pb_22->setAutoFillBackground(true);
        pb_22->setFlat(true);
        pb_23 = new QPushButton(Play);
        pb_23->setObjectName(QString::fromUtf8("pb_23"));
        pb_23->setGeometry(QRect(810, 120, 91, 161));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette30.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_23->setPalette(palette30);
        pb_23->setAutoFillBackground(true);
        pb_23->setFlat(true);
        pb_24 = new QPushButton(Play);
        pb_24->setObjectName(QString::fromUtf8("pb_24"));
        pb_24->setGeometry(QRect(900, 120, 91, 161));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette31.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_24->setPalette(palette31);
        pb_24->setAutoFillBackground(true);
        pb_24->setFlat(true);
        pb_25 = new QPushButton(Play);
        pb_25->setObjectName(QString::fromUtf8("pb_25"));
        pb_25->setGeometry(QRect(990, 120, 91, 161));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette32.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_25->setPalette(palette32);
        pb_25->setAutoFillBackground(true);
        pb_25->setFlat(true);
        pb_26 = new QPushButton(Play);
        pb_26->setObjectName(QString::fromUtf8("pb_26"));
        pb_26->setGeometry(QRect(1080, 120, 91, 161));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_26->setPalette(palette33);
        pb_26->setAutoFillBackground(true);
        pb_26->setFlat(true);
        pb_Move_1 = new QPushButton(Play);
        pb_Move_1->setObjectName(QString::fromUtf8("pb_Move_1"));
        pb_Move_1->setGeometry(QRect(330, 350, 91, 161));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette34.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_Move_1->setPalette(palette34);
        pb_Move_1->setAutoFillBackground(true);
        pb_Move_1->setFlat(true);
        pb_Move_2 = new QPushButton(Play);
        pb_Move_2->setObjectName(QString::fromUtf8("pb_Move_2"));
        pb_Move_2->setGeometry(QRect(450, 350, 91, 161));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_Move_2->setPalette(palette35);
        pb_Move_2->setAutoFillBackground(true);
        pb_Move_2->setFlat(true);
        pb_Move_3 = new QPushButton(Play);
        pb_Move_3->setObjectName(QString::fromUtf8("pb_Move_3"));
        pb_Move_3->setGeometry(QRect(570, 350, 91, 161));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette36.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_Move_3->setPalette(palette36);
        pb_Move_3->setAutoFillBackground(true);
        pb_Move_3->setFlat(true);
        pb_Move_4 = new QPushButton(Play);
        pb_Move_4->setObjectName(QString::fromUtf8("pb_Move_4"));
        pb_Move_4->setGeometry(QRect(690, 350, 91, 161));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        pb_Move_4->setPalette(palette37);
        pb_Move_4->setAutoFillBackground(true);
        pb_Move_4->setFlat(true);
        lblTricksWonNS = new QLabel(Play);
        lblTricksWonNS->setObjectName(QString::fromUtf8("lblTricksWonNS"));
        lblTricksWonNS->setGeometry(QRect(10, 520, 262, 24));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette38.setBrush(QPalette::Active, QPalette::Text, brush8);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette38.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette38.setBrush(QPalette::Inactive, QPalette::Text, brush8);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette38.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::Text, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette38.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush10);
#endif
        lblTricksWonNS->setPalette(palette38);
        lblTricksWonNS->setFont(font10);
        lblTricksWonNS->setAutoFillBackground(false);
        lblTricksWonNS->setTextFormat(Qt::PlainText);
        lblTricksWonEW = new QLabel(Play);
        lblTricksWonEW->setObjectName(QString::fromUtf8("lblTricksWonEW"));
        lblTricksWonEW->setGeometry(QRect(10, 550, 262, 24));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::WindowText, brush8);
        palette39.setBrush(QPalette::Active, QPalette::Text, brush8);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette39.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette39.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette39.setBrush(QPalette::Inactive, QPalette::Text, brush8);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette39.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette39.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette39.setBrush(QPalette::Disabled, QPalette::Text, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette39.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush10);
#endif
        lblTricksWonEW->setPalette(palette39);
        lblTricksWonEW->setFont(font10);
        lblTricksWonEW->setAutoFillBackground(false);
        lblTricksWonEW->setTextFormat(Qt::PlainText);
        stackedWidget->addWidget(Play);
        pb_14->raise();
        pb_15->raise();
        pb_16->raise();
        pb_17->raise();
        pb_18->raise();
        pb_19->raise();
        pb_26->raise();
        pb_25->raise();
        pb_24->raise();
        pb_23->raise();
        pb_22->raise();
        pb_21->raise();
        pb_20->raise();
        pb_13->raise();
        pb_12->raise();
        pb_11->raise();
        pb_10->raise();
        pb_9->raise();
        pb_8->raise();
        pb_7->raise();
        pb_6->raise();
        pb_5->raise();
        pb_4->raise();
        pb_3->raise();
        pb_2->raise();
        pb_1->raise();
        lblInfoPlay->raise();
        lblTeam->raise();
        lblPlayer->raise();
        lblOpp2->raise();
        lblOpp1->raise();
        lblOpp2Name->raise();
        lblNameTeam->raise();
        lblOpp1Name->raise();
        lblNamePlayer->raise();
        pushButton_Score->raise();
        pushButton_Abandon->raise();
        layoutWidget1->raise();
        lblRoundInfo->raise();
        pushButton_BackAuction->raise();
        pb_Move_1->raise();
        pb_Move_2->raise();
        pb_Move_3->raise();
        pb_Move_4->raise();
        lblTricksWonNS->raise();
        lblTricksWonEW->raise();

        horizontalLayout_2->addWidget(stackedWidget);


        retranslateUi(GameScreen);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(GameScreen);
    } // setupUi

    void retranslateUi(QDialog *GameScreen)
    {
        GameScreen->setWindowTitle(QCoreApplication::translate("GameScreen", "Dialog", nullptr));
        lblInfo->setText(QCoreApplication::translate("GameScreen", "Host: John Smit Server IP: 192.168.1.3 Port Number: 3 Password: password123", nullptr));

        const bool __sortingEnabled = tableBids->isSortingEnabled();
        tableBids->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem = tableBids->item(0, 0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("GameScreen", "\342\231\243", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableBids->item(0, 1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("GameScreen", "\342\231\246", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableBids->item(0, 2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("GameScreen", "\342\231\245", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableBids->item(0, 3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("GameScreen", "\342\231\240", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableBids->item(0, 4);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("GameScreen", "NT", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableBids->item(1, 0);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("GameScreen", "\342\231\243", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableBids->item(1, 1);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("GameScreen", "\342\231\246", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableBids->item(1, 2);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("GameScreen", "\342\231\245", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableBids->item(1, 3);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("GameScreen", "\342\231\240", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableBids->item(1, 4);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("GameScreen", "NT", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableBids->item(2, 0);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("GameScreen", "\342\231\243", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableBids->item(2, 1);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("GameScreen", "\342\231\246", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableBids->item(2, 2);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("GameScreen", "\342\231\245", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableBids->item(2, 3);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("GameScreen", "\342\231\240", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableBids->item(2, 4);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("GameScreen", "NT", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableBids->item(3, 0);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("GameScreen", "\342\231\243", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableBids->item(3, 1);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("GameScreen", "\342\231\246", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableBids->item(3, 2);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("GameScreen", "\342\231\245", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableBids->item(3, 3);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("GameScreen", "\342\231\240", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableBids->item(3, 4);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("GameScreen", "NT", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableBids->item(4, 0);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("GameScreen", "\342\231\243", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableBids->item(4, 1);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("GameScreen", "\342\231\246", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tableBids->item(4, 2);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("GameScreen", "\342\231\245", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tableBids->item(4, 3);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("GameScreen", "\342\231\240", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = tableBids->item(4, 4);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("GameScreen", "NT", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tableBids->item(5, 0);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("GameScreen", "\342\231\243", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tableBids->item(5, 1);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("GameScreen", "\342\231\246", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = tableBids->item(5, 2);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("GameScreen", "\342\231\245", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = tableBids->item(5, 3);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("GameScreen", "\342\231\240", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = tableBids->item(5, 4);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("GameScreen", "NT", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = tableBids->item(6, 0);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("GameScreen", "\342\231\243", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = tableBids->item(6, 1);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("GameScreen", "\342\231\246", nullptr));
        QTableWidgetItem *___qtablewidgetitem32 = tableBids->item(6, 2);
        ___qtablewidgetitem32->setText(QCoreApplication::translate("GameScreen", "\342\231\245", nullptr));
        QTableWidgetItem *___qtablewidgetitem33 = tableBids->item(6, 3);
        ___qtablewidgetitem33->setText(QCoreApplication::translate("GameScreen", "\342\231\240", nullptr));
        QTableWidgetItem *___qtablewidgetitem34 = tableBids->item(6, 4);
        ___qtablewidgetitem34->setText(QCoreApplication::translate("GameScreen", "NT", nullptr));
        tableBids->setSortingEnabled(__sortingEnabled);

        pushButton_Pass->setText(QCoreApplication::translate("GameScreen", "Pass", nullptr));
        pushButton_Double->setText(QCoreApplication::translate("GameScreen", "Double", nullptr));
        pushButton_Bid->setText(QCoreApplication::translate("GameScreen", "Place Bid", nullptr));
        pushButton_Play->setText(QCoreApplication::translate("GameScreen", "OK", nullptr));
        lblContract->setText(QCoreApplication::translate("GameScreen", "Contract: 7 No Trump", nullptr));
        lblDeclarer->setText(QCoreApplication::translate("GameScreen", "Declarer: South", nullptr));
        lblDummy->setText(QCoreApplication::translate("GameScreen", "Dummy: North", nullptr));
        lblDouble->setText(QString());
        pushButton_ViewCards->setText(QCoreApplication::translate("GameScreen", "View Cards", nullptr));
        pushButton_Redouble->setText(QCoreApplication::translate("GameScreen", "Redouble", nullptr));
        QTableWidgetItem *___qtablewidgetitem35 = tableSequence->horizontalHeaderItem(0);
        ___qtablewidgetitem35->setText(QCoreApplication::translate("GameScreen", "North", nullptr));
        QTableWidgetItem *___qtablewidgetitem36 = tableSequence->horizontalHeaderItem(1);
        ___qtablewidgetitem36->setText(QCoreApplication::translate("GameScreen", "East", nullptr));
        QTableWidgetItem *___qtablewidgetitem37 = tableSequence->horizontalHeaderItem(2);
        ___qtablewidgetitem37->setText(QCoreApplication::translate("GameScreen", "South", nullptr));
        QTableWidgetItem *___qtablewidgetitem38 = tableSequence->horizontalHeaderItem(3);
        ___qtablewidgetitem38->setText(QCoreApplication::translate("GameScreen", "West", nullptr));
        lblPosition->setText(QCoreApplication::translate("GameScreen", "Position: South", nullptr));
        lblInfoPlay->setText(QCoreApplication::translate("GameScreen", "Host: John Smit Server IP: 192.168.1.3 Port Number: 3 Password: password123", nullptr));
        lblTeam->setText(QCoreApplication::translate("GameScreen", "North (Dummy)", nullptr));
        lblPlayer->setText(QCoreApplication::translate("GameScreen", "South (Declarer)", nullptr));
        lblOpp2->setText(QCoreApplication::translate("GameScreen", " West", nullptr));
        lblOpp1->setText(QCoreApplication::translate("GameScreen", "East", nullptr));
        lblOpp2Name->setText(QCoreApplication::translate("GameScreen", "Victor Matfield", nullptr));
        lblNameTeam->setText(QCoreApplication::translate("GameScreen", "Jean de Villiers", nullptr));
        lblOpp1Name->setText(QCoreApplication::translate("GameScreen", "Bryan Habana", nullptr));
        lblNamePlayer->setText(QCoreApplication::translate("GameScreen", "John Smit", nullptr));
        pushButton_Score->setText(QCoreApplication::translate("GameScreen", "View Scoreboard", nullptr));
        pushButton_Abandon->setText(QCoreApplication::translate("GameScreen", "Abandon match", nullptr));
        lblVulnerable->setText(QCoreApplication::translate("GameScreen", "Vulnerable: North/South", nullptr));
        lblPoints->setText(QCoreApplication::translate("GameScreen", "Points: Standard (No Double)", nullptr));
        lblContractPlay->setText(QCoreApplication::translate("GameScreen", "Contract: 7 No Trump", nullptr));
        lblRoundInfo->setText(QCoreApplication::translate("GameScreen", "NS won the round", nullptr));
        pushButton_BackAuction->setText(QCoreApplication::translate("GameScreen", "Back to Auction", nullptr));
        pb_1->setText(QString());
        pb_2->setText(QString());
        pb_3->setText(QString());
        pb_4->setText(QString());
        pb_5->setText(QString());
        pb_6->setText(QString());
        pb_7->setText(QString());
        pb_8->setText(QString());
        pb_9->setText(QString());
        pb_10->setText(QString());
        pb_11->setText(QString());
        pb_12->setText(QString());
        pb_13->setText(QString());
        pb_14->setText(QString());
        pb_15->setText(QString());
        pb_16->setText(QString());
        pb_17->setText(QString());
        pb_18->setText(QString());
        pb_19->setText(QString());
        pb_20->setText(QString());
        pb_21->setText(QString());
        pb_22->setText(QString());
        pb_23->setText(QString());
        pb_24->setText(QString());
        pb_25->setText(QString());
        pb_26->setText(QString());
        pb_Move_1->setText(QString());
        pb_Move_2->setText(QString());
        pb_Move_3->setText(QString());
        pb_Move_4->setText(QString());
        lblTricksWonNS->setText(QCoreApplication::translate("GameScreen", "Vulnerable: North/South", nullptr));
        lblTricksWonEW->setText(QCoreApplication::translate("GameScreen", "Vulnerable: North/South", nullptr));
    } // retranslateUi

};

namespace Ui {
    class GameScreen: public Ui_GameScreen {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GAMESCREEN_H
